name: Testworkflow

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: workflow_dispatch

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
    - name: job1
      run: echo "This is my first Job"
    
  my_second_job:
    runs-on: ubuntu-latest
    steps:
    - name: job2
      run: echo "This is my 2nd Job"
